### ISSUE TITLE
[Feature] Stop cover from happening on templates

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-token-cover#14]
Just tried this mod last night and something I didn't see coming was dealing with cover prompts when players where using aoe spells. I took a glance at the settings and I didn't see anything jump out at me to deal with this.

Anyway to disable cover from happening on template targeting?

**Comment by caewok** [comment]
What module are you using to get template targeting? Walled Templates? Something else?

**Comment by TrofimSelbs** [comment]
I could reproduce this issue with this list of modules:

- dlopen
- lib - Color Settings
- libWrapper
- routinglib
- socketlib
- Midi QOL
- Alternative Token Cover
- Alternative Token Visibility

Other modules were disabled as I was using Find Culprit

**Comment by caewok** [comment]
I added some more intentional handling of measured templates in v0.9.3. There is a toggle in settings; when enabled, you can hover over templates to see the cover were the template to reach any given token. You will see something similar when dragging templates upon creation or when moving them. If you have midiqol module enabled, you can enable cover on specific spells.
