### ISSUE TITLE
[PF2E] Unable to edit greater cover type in book control

### ISSUE THREAD

**Issue by weepingminotaur** [caewok/fvtt-token-cover#22]
Trying to modify the values for % or Priority doesn't work for greater cover. It always revert to the default. 

Also, the default value for greater cover (1) ensures that greater cover will never be applied. It should probably be something high but not a whole number, like 0.85.

**Comment by weepingminotaur** [comment]
OK, now modifying the values seems to work? Very weird.

**Comment by caewok** [comment]
It is intentional that greater cover for PF2e is set to 1. Under default PF2e rules, cover is measured from viewer to token center --- i.e., a single line. So one either has cover or not. Lesser cover can be determined by looking at tokens that block. But greater cover requires checking the defender for take cover action. I will make a new issue to add that. 

FYI, I still need to figure out how to convince PF2e to use the item that I add as the cover effect. The item seems correct, but PF2e refuses to display it on the token sheet despite it being in the token's list of items. So I am missing something about what PF2e expects when adding an item to a character.
